### ISSUE TITLE
MultiGPU Issues

### ISSUE THREAD

**Issue by mckinlec** [Juice-Labs/Juice-Labs#90]
I only have 2 GPUs, but 4 are listed. I cannot get this system to work with multiple GPUs, with a single GPU it works fine, but with multiple  GPUs, the program I'm using doesn't work. It works fine when I use one GPU with Juice, as well as working fine with 2GPUs and not using Juice

<img width="867" alt="image" src="https://github.com/Juice-Labs/Juice-Labs/assets/112263595/35403e0b-6d53-4abd-9123-5f63892bb1e7">

The program is automatic1111.

the error I get is `Traceback (most recent call last):
  File "C:\ai_tools\stable-diffusion-webui-1\launch.py", line 39, in <module>
    main()
  File "C:\ai_tools\stable-diffusion-webui-1\launch.py", line 30, in main
    prepare_environment()
  File "C:\ai_tools\stable-diffusion-webui-1\modules\launch_utils.py", line 314, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .`

**Comment by mckinlec** [comment]
Also of note, juicify nvidia-smi correctly shows both GPUs, and adding "pcibus": ["00000000:02:00.0"] makes no difference
